export const errorMessageMap = {
  LoginFormInvalid: '登录失败，账号或密码不正确！',
  AccountForbidden: '账户被禁用',
  FormInvalid: '提交的数据不完整或有误！',
  DataNotExist: '数据不存在！',
  DataExisted: '数据已存在！',
  'No Access': '没有权限！',
  NoPermission: '没有权限！',
  DataInUsing: '数据正在被使用，请先清理关联数据！',
  OldPasswordError: '旧密码错误！',
  UserNotInUsing: '用户已被停用！',
  CaptchaError: '验证码错误或者已失效！',
  UserNotExist: '用户不存在！',
  'Network Error': '连接失败.',
  FileSizeLimited1MB: '文件过大，请处理至1MB以内！',
  FileSizeLimited3MB: '文件过大，请处理至3MB以内！',
  ErrorFileNameLength: '文件名过长，请重命名后再上传！',
  ErrorFileTypeExcel: '文件类型错误，仅支持Excel类型文件！',
  ErrorFileTypeMedia: '文件类型错误，仅支持图片或者视频文件！',
  StatusLocked: "当前状态无法进行操作/无法操作至目标状态！",
  ErrorEmailFormat: '邮箱格式错误！',
  ErrorPhoneFormat: '手机号格式错误！',
  ErrorDateFormat: '日期格式错误！',
  CannotEditOrDelete: '选中数据无法被编辑或者修改！',
  LeaveBalanceNotEnough: '假期额度不足！',
  FatalError: '操作失败，系统发生错误！',
  SendCodeFailed: '发送失败，请稍后再试！',
  PunchClockIPError: '打卡IP不匹配！',
  DateOutRange: '超出了限制的时间范围！',
  SalaryCalculated: '无法进行当前操作！（工资已计算）',
  OverMaxCount: '登录失败次数过多，请30分钟后再次操作！',
  NoValidData: '没有有效的数据！'
}
